/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m.o.managmentoperatingsystem;

/**
 *
 * @author matsh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnEmployee = new javax.swing.JButton();
        btnDeduction = new javax.swing.JButton();
        btnContract = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEmployee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEmployee.setText("EMPLOYEE");
        jLayeredPane1.add(btnEmployee);
        btnEmployee.setBounds(780, 510, 280, 60);

        btnDeduction.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDeduction.setText("DEDUCTION");
        jLayeredPane1.add(btnDeduction);
        btnDeduction.setBounds(670, 590, 240, 60);

        btnContract.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnContract.setText("CONTRACT");
        jLayeredPane1.add(btnContract);
        btnContract.setBounds(930, 590, 260, 60);

        btnSalary.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalary.setText("SALARY");
        jLayeredPane1.add(btnSalary);
        btnSalary.setBounds(780, 670, 280, 70);

        btnI.setBackground(new java.awt.Color(51, 51, 255));
        btnI.setFont(new java.awt.Font("Segoe Script", 0, 48)); // NOI18N
        btnI.setForeground(new java.awt.Color(0, 0, 204));
        btnI.setText("i");
        jLayeredPane1.add(btnI);
        btnI.setBounds(1080, 40, 80, 70);
        jLayeredPane1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1200, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContract;
    private javax.swing.JButton btnDeduction;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnSalary;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
